### ISSUE TITLE
sup-Files without .sup file extension cannot be opened

### ISSUE THREAD

**Issue by bluemoehre** [mjuhasz/BDSup2Sub#27]
well it is sometimes a little bit anoying i have to rename the files first. maybe u should check the file's mime type to determine if it is compatible.

**Comment by mjuhasz** [comment]
The file open dialog has a filter activated by default so it only shows files with idx, sup, ifo, xml and sub extension.
You can change it in the dropdown list to 'All Files' and then you can open the sup file even without the extension. It works for both blu-ray sup files and dvd sup files. In the latter case you have to have the ifo file in the same folder with the same name, e.g. subtitle.sup and subtitle.ifo or subtitle and subtitle.ifo
As for your suggestion, there is no official mimetype for sup files.

**Comment by bluemoehre** [comment]
Ah, works in 5.0.0 now.. didn't work in 4.0.1.
