### ISSUE TITLE
Hotkey navigation for edit frame window

### ISSUE THREAD

**Issue by bluemoehre** [mjuhasz/BDSup2Sub#28]
if u have to edit a lot of subtitles and need to check or uncheck a lot of settings/flags i would like to have the possibility to navigate with hotkeys.

**Comment by mjuhasz** [comment]
Thank you for your report. The latest release (v.5.1.0) improves the keyboard navigation on all platforms. On the Edit Frame dialog all buttons have a shortcut set (the character underlined, and for the navigation the left/right and PageUp/PageDown keys).
If you have a use case for which you are still missing shortcut keys feel free to comment on this ticket.
