### ISSUE TITLE
Global forced flag "Set all" broken

### ISSUE THREAD

**Issue by beeeeswax** [mjuhasz/BDSup2Sub#33]
In 5.x and even the latest beta, the "Set all" option doesn't work.

In 5.x if you open a .sup file and set "Force all" to "Set all" then press OK, set your output format and the save the new .sup, no forced flags are set.  

Also, before you save, if you go back into Conversion Settings, the "Force all" option has reverted to "keep".  Changing back to "Set all" -> OK then going back into Conversion Settings, you'll see it has reset once again.

Works fine in 4.0.1.

**Comment by mjuhasz** [comment]
Thank you for your report. This issue has been fixed on master in commit e84c7eaa4bcf3321123d238a8d5e5932d9c28f57

You can download the latest snapshot version which already contains this fix (see Downloads section on the wiki).

**Comment by beeeeswax** [comment]
Thanks for the speedy fix.
