### ISSUE TITLE
Resolution conversion broken in 5.1.0

### ISSUE THREAD

**Issue by indicosius** [mjuhasz/BDSup2Sub#35]
With the latest version of BDSup2sub (510) I am unable to convert a blu-ray subtitle to dvd subtitle. In the conversion options dialog I want to convert to NTSC (720x480). I choose NTSC (720x480) as the resolution but the subtitle does not get converted to NTSC (720x480). The subtitle keeps getting the same resolution as the source (1920x1080) no matter what setting I choose. I had no problem with the previous version of BDSup2sub (5.0.0)

**Comment by mjuhasz** [comment]
Thank you for reporting the issue.
I have fixed it in commit 9879fa259efb17f7f3c31a0a22d847df6eb385df

The latest snapshot version contains this fix. You can get it by visiting the Download page: https://github.com/mjuhasz/BDSup2Sub/wiki/Download
and clicking on the "Latest snapshot version for testers" link.
