### ISSUE TITLE
Index 0 out of bounds

### ISSUE THREAD

**Issue by ghost** [mjuhasz/BDSup2Sub#40]
Hello. When trying to open an IDX/SUB file, BDSup2Sub gives me the following error: "Index 0 out of bounds". Can you take a look at the file and see if you can support it later on? I tried many other software solutions and all of them fail. Thank you in advance.

http://www.mediafire.com/?69vuxcuw3hduuar

**Comment by ghost** [comment]
Your files are completely borked. How exactly did you create that?  The IDX file should be plain text but is full of binary junk when opened in Notepad++.  There's nothing that can be done when even the Vobsub tools can't open or make any sense of it. Your files are irreparably broken and you need to recreate them in a non-broken manner.

**Comment by mjuhasz** [comment]
paradoxic4l is right. There is not much I can do.
