### ISSUE TITLE
Add support for an additional blu-ray subtitle format

### ISSUE THREAD

**Issue by andrej-peterka** [mjuhasz/BDSup2Sub#5]
I ripped a SUP file from a Blu-ray yesterday (using eac3to 3.24) and BDSup2Sub (4.0.1) is having some problems handling it.

The SUP in question:
http://dl.dropbox.com/u/132558/suptitle/chatroom.sup

This is the log file that BDSup2Sub generates when opening the stream:
http://pastebin.com/GNr5gUiW

The problem is that BDSup2Sub gives incorrect timing information for some subtitles.
For example, the very first subtitle is reported to last almost 2 minutes, while it should only be a couple of seconds.

Apparently, it's some weird SUP format as the [SupTitle, the AviSynth plugin](http://www.zachsaw.com/?pg=suptitle_pgs_avisynth_plugin) also had some problems handling the file.

I reported the issue to the author yesterday and he was able to fix it. See the topic here:
http://zachsaw.com/forum/viewtopic.php?f=14&t=327

The filter now correctly handles the file and gets the timings right.

**Comment by amichaelt** [comment]
The fix for this problem is actually pretty simple.  You need to remove the line:

picTmp.endTime = ptsPCS;

from SupBD.java at line 274.  Found the fix within SubtitleEdit's code that was using BDSup2Sub's code.

**Comment by mjuhasz** [comment]
Fixed in master 01ed59e4ec8d7ee713f2df22a1cd98e9040d1db0
Thanks for amichaelt for the contribution!
