### ISSUE TITLE
Document how to get started or include jar building script

### ISSUE THREAD

**Issue by rajb245** [mjuhasz/BDSup2Sub#58]
I cloned this repo, but my Java is rusty. I know that if the jar file were made, I could run it with
`java -jar bdsup2sub.jar`

However, there is no jar in the repo. A some kind of a "build" script (Makefile?) that created the jar file from the sources would be nice to put in the repo. Alternately, the wiki could have some build instructions for people who don't work with java.

**Comment by Seegras** [comment]
Yes, how are we supposed to build that? maven, gradle, ant, even a makefile? 

`mkdir build; javac -d ./build *.java `

is not really it.

**Comment by rajb245** [comment]
@Seegras For what its worth, it seems that this project has been unmaintained for years.

**Comment by Seegras** [comment]
Yes, but right now, I have nothing else for the job. https://github.com/amichaeltm/BDSup2SubPlusPlus does not compile with modern QT versions.

**Comment by fasiha** [comment]
Per https://github.com/mjuhasz/BDSup2Sub/issues/60#issuecomment-619586778 I was able to download a JAR from https://gitlab.com/spirillen/video-convertion/-/tree/master which can be run via `java -jar BDSup2Sub512.jar`

**Comment by cannonball1911** [comment]
On the wiki for this repo is a [download tab](https://github.com/mjuhasz/BDSup2Sub/wiki/Download) where you can download the v5.1.2, older versions of BDSup2Sub and even an alpha/beta for v5.2 (which probably will never be finished)

**Comment by Seegras** [comment]
> On the wiki for this repo is a [download tab](https://github.com/mjuhasz/BDSup2Sub/wiki/Download) where you can download the v5.1.2, older versions of BDSup2Sub and even an alpha/beta for v5.2 (which probably will never be finished)

Yes, but how do you COMPILE from source? There is no make/ant/maven/gradle file.

**Comment by rajb245** [comment]
Project is dead for 10 years, I don't care if this ever gets fixed, closing
