### ISSUE TITLE
Potential license violation

### ISSUE THREAD

**Issue by ghost** [mjuhasz/BDSup2Sub#8]
Perusing through your changes I've noticed you've stripped the LGPL license on the PNGEncoder.java class and put it under Apachev2.  Did you have permission from the original author to do so?  Because if you didn't that's a license violation.

**Comment by mjuhasz** [comment]
Thank you for drawing my attention to this. I was trying to use to same template header everywhere but I realized that I stripped out 0xdeadbeef's name in some files and some files like the one you found had custom headers.
I'll revisit and restore the incorrect license headers before release.

**Comment by mjuhasz** [comment]
Fixed in master 4a95dc1f9c2df1717e4bc3b2bad0b83b76b1e151
